import { v4 as uuidv4 } from "uuid"
import type { Recipe } from "./types"

// Função auxiliar para criar slugs consistentes a partir dos títulos
function createSlug(title: string): string {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '-');
}

export const sampleRecipes: Recipe[] = [
  {
    key: "classic-spaghetti-bolognese",
    title: "Classic Spaghetti Bolognese",
    category: "Dinner",
    description: "A rich and hearty Italian pasta dish with a meaty tomato sauce.",
    prepTime: 15,
    cookTime: 45,
    servings: 4,
    ingredients: [
      { key: uuidv4(), name: "ground beef", quantity: "500", unit: "g" },
      { key: uuidv4(), name: "onion, finely chopped", quantity: "1", unit: "medium" },
      { key: uuidv4(), name: "garlic cloves, minced", quantity: "2", unit: "" },
      { key: uuidv4(), name: "carrots, finely diced", quantity: "2", unit: "medium" },
      { key: uuidv4(), name: "celery stalks, finely diced", quantity: "2", unit: "" },
      { key: uuidv4(), name: "tomato paste", quantity: "2", unit: "tbsp" },
      { key: uuidv4(), name: "crushed tomatoes", quantity: "800", unit: "g" },
      { key: uuidv4(), name: "beef stock", quantity: "250", unit: "ml" },
      { key: uuidv4(), name: "dried oregano", quantity: "1", unit: "tsp" },
      { key: uuidv4(), name: "dried basil", quantity: "1", unit: "tsp" },
      { key: uuidv4(), name: "bay leaf", quantity: "1", unit: "" },
      { key: uuidv4(), name: "spaghetti", quantity: "400", unit: "g" },
      { key: uuidv4(), name: "Parmesan cheese, grated", quantity: "50", unit: "g" },
      { key: uuidv4(), name: "salt and pepper", quantity: "", unit: "to taste" },
    ],
    instructions: [
      "Heat olive oil in a large pot over medium heat. Add onions, carrots, and celery, and cook until softened, about 5 minutes.",
      "Add garlic and cook for another minute until fragrant.",
      "Increase heat to medium-high and add ground beef. Cook until browned, breaking it up with a spoon.",
      "Stir in tomato paste and cook for 1-2 minutes.",
      "Add crushed tomatoes, beef stock, oregano, basil, and bay leaf. Season with salt and pepper.",
      "Reduce heat to low, cover, and simmer for 30-45 minutes, stirring occasionally.",
      "Meanwhile, cook spaghetti according to package instructions until al dente.",
      "Drain pasta and serve topped with the bolognese sauce and grated Parmesan cheese.",
    ],
    tags: ["Italian", "Pasta", "Beef", "Family Meal"],
    createdAt: new Date(2023, 5, 15).toISOString(),
  },
  {
    key: "avocado-toast-with-poached-eggs",
    title: "Avocado Toast with Poached Eggs",
    category: "Breakfast",
    description: "A nutritious and delicious breakfast that's quick to prepare.",
    prepTime: 10,
    cookTime: 5,
    servings: 2,
    ingredients: [
      { key: uuidv4(), name: "ripe avocados", quantity: "1", unit: "large" },
      { key: uuidv4(), name: "lemon juice", quantity: "1", unit: "tbsp" },
      { key: uuidv4(), name: "red pepper flakes", quantity: "1/4", unit: "tsp" },
      { key: uuidv4(), name: "sourdough bread", quantity: "2", unit: "slices" },
      { key: uuidv4(), name: "eggs", quantity: "2", unit: "large" },
      { key: uuidv4(), name: "white vinegar", quantity: "1", unit: "tbsp" },
      { key: uuidv4(), name: "salt and pepper", quantity: "", unit: "to taste" },
      { key: uuidv4(), name: "fresh chives, chopped", quantity: "1", unit: "tbsp" },
    ],
    instructions: [
      "Fill a medium pot with water and bring to a gentle simmer. Add vinegar.",
      "Toast the bread slices until golden and crisp.",
      "In a small bowl, mash the avocado with lemon juice, salt, and pepper.",
      "Spread the mashed avocado on the toast slices.",
      "Crack each egg into a small cup. Create a gentle whirlpool in the simmering water and carefully slide in the eggs one at a time.",
      "Poach for 3-4 minutes for a runny yolk.",
      "Remove eggs with a slotted spoon and place on top of the avocado toast.",
      "Sprinkle with red pepper flakes, additional salt and pepper, and chopped chives.",
    ],
    tags: ["Breakfast", "Healthy", "Quick", "Vegetarian"],
    createdAt: new Date(2023, 7, 22).toISOString(),
  },
  {
    key: "chocolate-chip-cookies",
    title: "Chocolate Chip Cookies",
    category: "Dessert",
    description: "Classic homemade chocolate chip cookies that are soft in the middle and crispy on the edges.",
    prepTime: 15,
    cookTime: 12,
    servings: 24,
    ingredients: [
      { key: uuidv4(), name: "all-purpose flour", quantity: "280", unit: "g" },
      { key: uuidv4(), name: "baking soda", quantity: "1", unit: "tsp" },
      { key: uuidv4(), name: "salt", quantity: "1/2", unit: "tsp" },
      { key: uuidv4(), name: "unsalted butter, softened", quantity: "225", unit: "g" },
      { key: uuidv4(), name: "granulated sugar", quantity: "150", unit: "g" },
      { key: uuidv4(), name: "brown sugar", quantity: "150", unit: "g" },
      { key: uuidv4(), name: "vanilla extract", quantity: "2", unit: "tsp" },
      { key: uuidv4(), name: "large eggs", quantity: "2", unit: "" },
      { key: uuidv4(), name: "chocolate chips", quantity: "350", unit: "g" },
    ],
    instructions: [
      "Preheat oven to 350°F (175°C). Line baking sheets with parchment paper.",
      "In a medium bowl, whisk together flour, baking soda, and salt.",
      "In a large bowl, cream together butter, granulated sugar, and brown sugar until light and fluffy.",
      "Beat in eggs one at a time, then stir in vanilla.",
      "Gradually blend in the dry ingredients.",
      "Fold in chocolate chips.",
      "Drop rounded tablespoons of dough onto the prepared baking sheets.",
      "Bake for 10-12 minutes, or until edges are golden but centers are still soft.",
      "Allow cookies to cool on baking sheet for 2 minutes before transferring to wire racks.",
    ],
    tags: ["Dessert", "Baking", "Cookies", "Kid-Friendly"],
    createdAt: new Date(2023, 9, 5).toISOString(),
  },
  {
    key: "thai-green-curry-with-chicken",
    title: "Thai Green Curry with Chicken",
    category: "Dinner",
    description: "A fragrant and spicy Thai curry with tender chicken and vegetables.",
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    ingredients: [
      { key: uuidv4(), name: "chicken breasts, cut into chunks", quantity: "500", unit: "g" },
      { key: uuidv4(), name: "green curry paste", quantity: "3", unit: "tbsp" },
      { key: uuidv4(), name: "coconut milk", quantity: "400", unit: "ml" },
      { key: uuidv4(), name: "chicken stock", quantity: "200", unit: "ml" },
      { key: uuidv4(), name: "fish sauce", quantity: "2", unit: "tbsp" },
      { key: uuidv4(), name: "palm sugar or brown sugar", quantity: "1", unit: "tbsp" },
      { key: uuidv4(), name: "kaffir lime leaves", quantity: "4", unit: "" },
      { key: uuidv4(), name: "Thai basil leaves", quantity: "1", unit: "handful" },
      { key: uuidv4(), name: "bell peppers, sliced", quantity: "2", unit: "" },
      { key: uuidv4(), name: "bamboo shoots, drained", quantity: "1", unit: "can" },
      { key: uuidv4(), name: "vegetable oil", quantity: "2", unit: "tbsp" },
      { key: uuidv4(), name: "jasmine rice, cooked", quantity: "2", unit: "cups" },
    ],
    instructions: [
      "Heat oil in a large pan or wok over medium-high heat.",
      "Add green curry paste and cook for 1-2 minutes until fragrant.",
      "Add chicken and cook until no longer pink on the outside, about 5 minutes.",
      "Pour in coconut milk and chicken stock, then add kaffir lime leaves.",
      "Bring to a simmer and cook for 10 minutes.",
      "Add bell peppers and bamboo shoots, and continue to simmer for 5 more minutes until chicken is cooked through and vegetables are tender.",
      "Stir in fish sauce and sugar, adjusting to taste.",
      "Remove from heat and stir in Thai basil leaves.",
      "Serve hot with jasmine rice.",
    ],
    tags: ["Thai", "Curry", "Spicy", "Asian"],
    createdAt: new Date(2023, 11, 12).toISOString(),
  },
  {
    key: "greek-salad",
    title: "Greek Salad",
    category: "Lunch",
    description: "A refreshing Mediterranean salad with crisp vegetables and tangy feta cheese.",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    ingredients: [
      { key: uuidv4(), name: "cucumber, chopped", quantity: "1", unit: "large" },
      { key: uuidv4(), name: "tomatoes, chopped", quantity: "4", unit: "medium" },
      { key: uuidv4(), name: "red onion, thinly sliced", quantity: "1/2", unit: "" },
      { key: uuidv4(), name: "green bell pepper, chopped", quantity: "1", unit: "" },
      { key: uuidv4(), name: "kalamata olives", quantity: "1/2", unit: "cup" },
      { key: uuidv4(), name: "feta cheese, cubed", quantity: "200", unit: "g" },
      { key: uuidv4(), name: "extra virgin olive oil", quantity: "1/4", unit: "cup" },
      { key: uuidv4(), name: "red wine vinegar", quantity: "2", unit: "tbsp" },
      { key: uuidv4(), name: "dried oregano", quantity: "1", unit: "tsp" },
      { key: uuidv4(), name: "salt and pepper", quantity: "", unit: "to taste" },
    ],
    instructions: [
      "In a large bowl, combine cucumber, tomatoes, red onion, bell pepper, and olives.",
      "In a small bowl, whisk together olive oil, red wine vinegar, oregano, salt, and pepper to make the dressing.",
      "Pour the dressing over the vegetables and toss gently to combine.",
      "Add the feta cheese cubes and toss very gently to avoid breaking them up too much.",
      "Serve immediately or refrigerate for up to 1 hour to allow flavors to meld.",
    ],
    tags: ["Greek", "Salad", "Vegetarian", "Healthy", "No-Cook"],
    createdAt: new Date(2024, 0, 8).toISOString(),
  },
  {
    key: "homemade-pizza",
    title: "Homemade Pizza",
    category: "Dinner",
    description: "Delicious homemade pizza with a crispy crust and your favorite toppings.",
    prepTime: 30,
    cookTime: 15,
    servings: 4,
    ingredients: [
      { key: uuidv4(), name: "all-purpose flour", quantity: "500", unit: "g" },
      { key: uuidv4(), name: "active dry yeast", quantity: "7", unit: "g" },
      { key: uuidv4(), name: "warm water", quantity: "300", unit: "ml" },
      { key: uuidv4(), name: "salt", quantity: "10", unit: "g" },
      { key: uuidv4(), name: "olive oil", quantity: "2", unit: "tbsp" },
      { key: uuidv4(), name: "tomato sauce", quantity: "1", unit: "cup" },
      { key: uuidv4(), name: "mozzarella cheese, shredded", quantity: "300", unit: "g" },
      { key: uuidv4(), name: "pepperoni slices", quantity: "100", unit: "g" },
      { key: uuidv4(), name: "bell peppers, sliced", quantity: "1", unit: "" },
      { key: uuidv4(), name: "mushrooms, sliced", quantity: "100", unit: "g" },
      { key: uuidv4(), name: "dried oregano", quantity: "1", unit: "tsp" },
      { key: uuidv4(), name: "fresh basil leaves", quantity: "10", unit: "" },
    ],
    instructions: [
      "In a large bowl, dissolve yeast in warm water and let sit for 5 minutes until foamy.",
      "Add flour, salt, and olive oil to the bowl and mix until a dough forms.",
      "Knead the dough on a floured surface for about 5-7 minutes until smooth and elastic.",
      "Place the dough in an oiled bowl, cover with a damp cloth, and let rise in a warm place for 1 hour or until doubled in size.",
      "Preheat oven to 475°F (245°C) with a pizza stone or baking sheet inside.",
      "Punch down the dough and divide it into 2 equal portions for two medium pizzas.",
      "Roll out each portion on a floured surface to your desired thickness.",
      "Transfer the dough to a piece of parchment paper or a floured pizza peel.",
      "Spread tomato sauce over the dough, leaving a small border for the crust.",
      "Sprinkle with mozzarella cheese and add your toppings of choice.",
      "Slide the pizza onto the preheated stone or baking sheet and bake for 12-15 minutes until the crust is golden and the cheese is bubbly.",
      "Remove from oven, sprinkle with fresh basil leaves, slice, and serve hot.",
    ],
    tags: ["Italian", "Pizza", "Family Meal", "Customizable"],
    createdAt: new Date(2024, 1, 20).toISOString(),
  },
  {
    key: "banana-smoothie-bowl",
    title: "Banana Smoothie Bowl",
    category: "Breakfast",
    description: "A nutritious and refreshing smoothie bowl topped with fresh fruits and granola.",
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    ingredients: [
      { key: uuidv4(), name: "frozen bananas", quantity: "2", unit: "medium" },
      { key: uuidv4(), name: "frozen berries", quantity: "1/2", unit: "cup" },
      { key: uuidv4(), name: "almond milk", quantity: "1/4", unit: "cup" },
      { key: uuidv4(), name: "protein powder (optional)", quantity: "1", unit: "scoop" },
      { key: uuidv4(), name: "fresh strawberries, sliced", quantity: "3", unit: "" },
      { key: uuidv4(), name: "blueberries", quantity: "1/4", unit: "cup" },
      { key: uuidv4(), name: "granola", quantity: "1/4", unit: "cup" },
      { key: uuidv4(), name: "chia seeds", quantity: "1", unit: "tsp" },
      { key: uuidv4(), name: "honey or maple syrup", quantity: "1", unit: "tsp" },
    ],
    instructions: [
      "In a blender, combine frozen bananas, frozen berries, almond milk, and protein powder (if using).",
      "Blend until smooth and creamy. The mixture should be thick enough to eat with a spoon.",
      "Pour the smoothie into a bowl.",
      "Top with sliced strawberries, blueberries, granola, and chia seeds.",
      "Drizzle with honey or maple syrup if desired.",
      "Serve immediately.",
    ],
    tags: ["Breakfast", "Smoothie", "Healthy", "Vegan", "No-Cook"],
    createdAt: new Date(2024, 2, 5).toISOString(),
  },
  {
    key: "beef-and-vegetable-stir-fry",
    title: "Beef and Vegetable Stir Fry",
    category: "Dinner",
    description: "A quick and flavorful stir fry with tender beef strips and crisp vegetables.",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    ingredients: [
      { key: uuidv4(), name: "beef sirloin, thinly sliced", quantity: "500", unit: "g" },
      { key: uuidv4(), name: "soy sauce", quantity: "3", unit: "tbsp" },
      { key: uuidv4(), name: "cornstarch", quantity: "1", unit: "tbsp" },
      { key: uuidv4(), name: "sesame oil", quantity: "1", unit: "tbsp" },
      { key: uuidv4(), name: "vegetable oil", quantity: "2", unit: "tbsp" },
      { key: uuidv4(), name: "garlic, minced", quantity: "3", unit: "cloves" },
      { key: uuidv4(), name: "ginger, minced", quantity: "1", unit: "tbsp" },
      { key: uuidv4(), name: "broccoli florets", quantity: "2", unit: "cups" },
      { key: uuidv4(), name: "bell peppers, sliced", quantity: "2", unit: "" },
      { key: uuidv4(), name: "carrots, julienned", quantity: "2", unit: "" },
      { key: uuidv4(), name: "snow peas", quantity: "1", unit: "cup" },
      { key: uuidv4(), name: "beef broth", quantity: "1/2", unit: "cup" },
      { key: uuidv4(), name: "oyster sauce", quantity: "2", unit: "tbsp" },
      { key: uuidv4(), name: "brown sugar", quantity: "1", unit: "tbsp" },
      { key: uuidv4(), name: "green onions, sliced", quantity: "3", unit: "" },
      { key: uuidv4(), name: "cooked rice", quantity: "4", unit: "cups" },
    ],
    instructions: [
      "In a bowl, mix beef with 1 tablespoon soy sauce and cornstarch. Let marinate for 10 minutes.",
      "In a small bowl, combine remaining soy sauce, beef broth, oyster sauce, and brown sugar.",
      "Heat 1 tablespoon vegetable oil in a large wok or skillet over high heat.",
      "Add beef and stir-fry until browned, about 2-3 minutes. Remove and set aside.",
      "Add remaining oil to the wok. Add garlic and ginger and stir-fry for 30 seconds until fragrant.",
      "Add broccoli, bell peppers, and carrots. Stir-fry for 3-4 minutes.",
      "Add snow peas and stir-fry for another minute.",
      "Return beef to the wok and add the sauce mixture.",
      "Cook, stirring, until sauce thickens slightly, about 2 minutes.",
      "Stir in sesame oil and green onions.",
      "Serve hot over cooked rice.",
    ],
    tags: ["Asian", "Stir Fry", "Beef", "Quick"],
    createdAt: new Date(2024, 2, 18).toISOString(),
  },
]

export function initializeSampleData() {
  try {
    // Check if recipes already exist in localStorage
    const existingRecipes = localStorage.getItem("recipes")

    // If no recipes exist, add sample data
    if (!existingRecipes || JSON.parse(existingRecipes).length === 0) {
      // Add a console log to help with debugging
      console.log("Initializing sample recipes with keys:", sampleRecipes.map(r => r.key));
      localStorage.setItem("recipes", JSON.stringify(sampleRecipes))
      return true
    }

    return false
  } catch (error) {
    console.error("Error initializing sample data:", error)
    return false
  }
}

